### ISSUE TITLE
反馈问题

### ISSUE THREAD

**Issue by SportPlusX** [journey-ad/wangEditor-Typecho-Plugin#1]
可视化编辑彩色字体，前段只能解析出HTML代码
![image](https://user-images.githubusercontent.com/15948273/35606293-3f9026f4-0689-11e8-91a7-779a0ec46588.png)
![image](https://user-images.githubusercontent.com/15948273/35606302-4825f794-0689-11e8-8e6c-3e88475e815e.png)

**Comment by journey-ad** [comment]
Typecho1.1 的 Markdown 解析器的问题，在`控制台-个人设置中`关闭`使用 Markdown 语法编辑和解析内容`
或装一个第三方 Markdown 解析插件试试，比如这个 [MDRuby-Typecho-Plugin](https://github.com/journey-ad/MDRuby-Typecho-Plugin)

**Comment by SportPlusX** [comment]
确实是Markdown 解析器的问题，关闭就好了
